[global]
# Global configuration options

# Development mode (set to false for production)
developmentMode = true

# Show warning when running in development mode
showWarningOnDirectExecution = false

[server]
# Server configuration
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200  # MB
maxMessageSize = 200  # MB

[browser]
# Browser behavior
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# UI theme configuration
primaryColor = "#FF6B35"      # Orange accent color
backgroundColor = "#FFFFFF"   # White background
secondaryBackgroundColor = "#F0F2F6"  # Light gray
textColor = "#262730"         # Dark text

[client]
# Client configuration
caching = true
showErrorDetails = true

[logger]
# Logging configuration
level = "info"

[runner]
# Script runner configuration
magicEnabled = true
installTracer = false
fixMatplotlib = true

[deprecation]
# Deprecation warnings
showfileUploaderEncoding = false
showImageFormat = false
